### ISSUE TITLE
OSError: [Errno 8] Exec format error with geckodriver on Kali Linux

### ISSUE THREAD

**Issue by code-bye** [b31ngD3v/bomberthon#1]
how to fix?
![image](https://user-images.githubusercontent.com/44205014/91872322-1e68a480-ec4e-11ea-92e7-5214a4b48459.png)

**Comment by b31ngD3v** [comment]
May I know which operating system you are using ?

**Comment by b31ngD3v** [comment]
32 Bit or 64 Bit ?

**Comment by code-bye** [comment]
64bit

**Comment by b31ngD3v** [comment]
Do you have firefox browser on your pc ?

**Comment by code-bye** [comment]
I have this one, it already came installed
![image](https://user-images.githubusercontent.com/44205014/91875299-af8d4a80-ec51-11ea-8184-6cf05273c513.png)

**Comment by b31ngD3v** [comment]
![Screenshot at 2020-09-01 21-22-33](https://user-images.githubusercontent.com/64733912/91875649-65c85280-ec99-11ea-8bf3-0e771e4438ae.png)
Did you give the executable permission before running ?

**Comment by b31ngD3v** [comment]
I think there is something wrong with this version of geckodriver (v0.26.0). I'm updating the geckodriver (v0.27.0). Give me 10 minutes.

**Comment by code-bye** [comment]
okok :D

**Comment by b31ngD3v** [comment]
Delete Previous Files, And Clone it Again. I Updated The Geckodriver.

**Comment by code-bye** [comment]
ok xd

**Comment by code-bye** [comment]
![image](https://user-images.githubusercontent.com/44205014/91880222-989d2700-ec56-11ea-85c5-cc0ab691fcdf.png)

not working for me idk why

**Comment by code-bye** [comment]
![image](https://user-images.githubusercontent.com/44205014/91881895-950a9f80-ec58-11ea-822b-b34e08a0064b.png)

I tried on windows and another error occurred

**Comment by b31ngD3v** [comment]
![photo_2020-09-01_22-33-19](https://user-images.githubusercontent.com/64733912/91884190-3c142900-eca3-11ea-9df7-140dd15a935b.jpg)
I think geckodriver doesn't support Kali Linux

**Comment by code-bye** [comment]
Which system would you recommend me to use?

**Comment by b31ngD3v** [comment]
Windows 8.1 - Windows 10
Linux :
Ubuntu Mate (Tested)
Ubuntu

**Comment by b31ngD3v** [comment]
Hey @code-bye I missed the comment on which you showed there are some errors when you try to run it on your windows machine. Make sure Chrome browser is installed in your windows system.
![Screenshot at 2020-09-01 23-03-58](https://user-images.githubusercontent.com/64733912/91886771-7384d480-eca7-11ea-98fb-2c661fe24e39.png)

**Comment by code-bye** [comment]
I have installed and tried, but it didn't work, I am installing the Ubuntu Mate that you recommended, I hope it works xd, thanks for your attention btw

**Comment by b31ngD3v** [comment]
![ss1 9](https://user-images.githubusercontent.com/64733912/91889305-3d495400-ecab-11ea-802e-0adcaf58dab1.PNG)
@code-bye

**Comment by code-bye** [comment]
@b31ngD3v I finished installing UbuntuMate and did all the steps as it says in the readme, and now I'm having this error when I run it
![image](https://user-images.githubusercontent.com/44205014/91890234-8b3b6900-ec65-11ea-9112-be64381d95e4.png)

**Comment by b31ngD3v** [comment]
try,
python3 bomberthon.py

**Comment by code-bye** [comment]
> try,
> python3 bomberthon.py

Now the script runs correctly, but the "spam sms" do not reach the cell phone number

**Comment by code-bye** [comment]
Maybe it doesn't work for Brazil?

**Comment by b31ngD3v** [comment]
It depends on mytoolstown api.
Our Team tried it. We tested it in Turkey, USA, UK, India, Pakistan.

**Comment by code-bye** [comment]
![image](https://user-images.githubusercontent.com/44205014/91891074-c5593a80-ec66-11ea-82ea-25d16b4bfae6.png)

Appears as done, but I didn't receive any sms

**Comment by b31ngD3v** [comment]
Can I close the issue ?

**Comment by code-bye** [comment]
> Can I close the issue ?

Yes, just one last question, how does Whatsapp bomber work?
and do you have a date for the Call bomber?

**Comment by b31ngD3v** [comment]
WhatsApp Bomber:
A pop up will open and it'll ask you to login via whatsapp web.
After logging in the program will do its work.
Call Bomber:
Sorry to say, there is no active api at this time and chances are very low. Probably we'll remove the option in the next update.

**Comment by code-bye** [comment]
> WhatsApp Bomber:
> A pop up will open and it'll ask you to login via whatsapp web.
> After logging in the program will do its work.
> Call Bomber:
> Sorry to say, there is no active api at this time and chances are very low. Probably we'll remove the option in the next update.

Ok, so I need to have a fake whatsapp to use, got it.
Do you know any method where I can create whatsapp without using my real number?

maybe using twilio or something like that wouldn't be possible(CallerBomb)?

**Comment by b31ngD3v** [comment]
> > WhatsApp Bomber:
> > A pop up will open and it'll ask you to login via whatsapp web.
> > After logging in the program will do its work.
> > Call Bomber:
> > Sorry to say, there is no active api at this time and chances are very low. Probably we'll remove the option in the next update.
> 
> Ok, so I need to have a fake whatsapp to use, got it.
> Do you know any method where I can create whatsapp without using my real number?
> 
> maybe using twilio or something like that wouldn't be possible(CallerBomb)?

You can use TextNow to create disposable us number. To know more search it on youtube.
No, for call bomber we can't use any service like twilo, because it is limited and auth. is reqiered.
