### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by xxharmanxx** [b31ngD3v/bomberthon#2]
Idk but it's showing a runtime error related to selenium , selenium.common.exceptions.sessionNotCreatedException : Message : unable to find matching set of capabilities . I am using Kali Linux fully updated. Please help

**Comment by b31ngD3v** [comment]
![image](https://user-images.githubusercontent.com/64733912/102627376-20f3f900-416e-11eb-8b80-580813d60cb8.jpg)
